### ISSUE TITLE
Pagina em branco - Não quebra o link

### ISSUE THREAD

**Issue by alex-coelho** [manualdousuario/marreta#1]
Olá!

O marreta mostra apenas uma página em branco com o link a seguir:

https://www.nexojornal.com.br/colunistas/2024/11/13/celular-rede-social-impacto-vida-social

**Comment by rghedin** [comment]
Hmmm, o Nexo usar hard paywall (precisa de login), um tipo que o Marreta não quebra.

Vamos atualizar o Marreta para devolver uma mensagem de erro em vez de mostrar uma página em branco.

**Comment by altendorfme** [comment]
Commitado: https://github.com/manualdousuario/marreta/commit/52985beac52270ec1cde413b9977ffd04c3f80d4
