### ISSUE TITLE
Pop up de cadastro Uol - Marreta não quebra

### ISSUE THREAD

**Issue by alex-coelho** [manualdousuario/marreta#2]
Olá! 

Após usar o marreta pra acessar uma notícia do Uol, o marreta continua exibindo o popup de bloqueio do site que exige cadastro (que não é de assinatura) para continuar lendo.

Link testado: https://noticias.uol.com.br/colunas/jose-roberto-de-toledo/2024/12/03/novo-ir-cobra-10-de-r-12-milhao-e-4-de-r-750-mil-veja-mais-taxas.htm

**Comment by altendorfme** [comment]
Correção feita na atualização 1.6.1: https://github.com/manualdousuario/marreta/commit/65ae33101d7d98abb48e88b4f32f294d82594588
