### ISSUE TITLE
Algumas marretas estão incompletas

### ISSUE THREAD

**Issue by raymuncb** [manualdousuario/marreta#3]
Por exemplo, a marreta https://marreta.pcdomanual.com/p/https://www.nytimes.com/2024/12/08/nyregion/new-jersey-state-police-slowdown.html?smtyp=cur&smid=bsky-nytimes ficou com o script de verificação de subscriber.

**Comment by raymuncb** [comment]
Ah compreendido. É que como o archive.today consegue ler, imaginei que
seria possível.


Em seg., 9 de dez. de 2024 às 13:32, Renan Altendorf <
***@***.***> escreveu:

**Comment by altendorfme** [comment]
Hum... Agora me pegou, vou analisar com mais carinho

**Comment by altendorfme** [comment]
Correção feita: https://github.com/manualdousuario/marreta/commit/d1582a351d2a9eb2080b31dba0f7444cabefb30c
Em breve será será empacotada com outras melhorias e sobe pra produção
