### ISSUE TITLE
Erro Generico ao tentar quebrar um paywall

### ISSUE THREAD

**Issue by arcanj0** [manualdousuario/marreta#4]
Quando tento acessar uma página, estou recebendo um erro genérico, redirecionando para esta página:

https://marreta.pcdomanual.com/?message=GENERIC_ERROR

A página em questão é https://www.stcatharinesstandard.ca/news/crime/gift-bags-and-blood-stains-part-2-honey-and-barry-shermans-killers-plan-was-to/article_73f7cbb7-13fb-5472-8be9-9b4af222d2e2.html

Ela funcionava perfeitamente bem dias atrás. Devem ter feito alguma mudança por parte deles.

Eu testei via bookmark no Chrome e também inserindo a URL direto no site marreta.pcdomanual.com

Se precisar de qualquer outra informação, me avise!

**Comment by altendorfme** [comment]
Já commitado, deve entrar em uma futura versão https://github.com/manualdousuario/marreta/commit/b5ac4c0036fb472169d5caa8e74ad2c03738030f
