### ISSUE TITLE
Folha de Sao Paulo com visual quebrado

### ISSUE THREAD

**Issue by aserighelli** [manualdousuario/marreta#5]
Logo que descobri a ferramenta funcionava perfeitamente para o site da Folha.

Recentemente (nao sei precisar quando) passou a desconfigurar o site inteiro.

URL para teste https://www1.folha.uol.com.br/blogs/cozinha-bruta/2024/12/arruinei-a-farofa-de-natal-da-minha-mae-com-o-raio-gourmetizador.shtml

**Comment by altendorfme** [comment]
Olá! Tenta verificar em anonimo, pode ser um bloqueio de extensão ou DNS

Validei nessa URL e está normal: https://marreta.pcdomanual.com/p/https%3A%2F%2Fwww1.folha.uol.com.br%2Fblogs%2Fcozinha-bruta%2F2024%2F12%2Farruinei-a-farofa-de-natal-da-minha-mae-com-o-raio-gourmetizador.shtml
![image](https://github.com/user-attachments/assets/6ec90c4a-30f4-442d-8eda-1f5c5a262f5e)

**Comment by aserighelli** [comment]
Desabilitando a extensao Privacy Badger volta a funcionar normalmente.
